name: GitHub Actions Build and Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.MY_DEPLOY_KEY }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: release # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          BUILD_SCRIPT: yarn &&  yarn build 
      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /data/www/temp
            mkdir /data/www/temp
            cd /data/www/temp
            git clone -b release https://github.com/ibwei/vue3-base/
            cd /data/www/temp/vue3-base
            mv dist/* /data/www/vue3
