name: GitHub Actions Build and Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.MY_DEPLOY_KEY }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: yarn &&  build &&  cp ./dist/index.html ./dist/404.html && echo "pro.abckey.com" > ./dist/CNAME
      - name: deploy to target directory
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
          repo: ibwei/vue3-base
        env:
          GITHUB_TOKEN: ${{ secrets.MY_DEPLOY_KEY }}
          GITHUB_PAT: ${{secrets.MY_DEPLOY_KEY}}
      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /data/www/temp
            mkdir /data/www/temp
            cd /data/www/temp
            git clone https://github.com/ibwei/vue3-base/
            cd /data/www/temp/vue3-base
            git checkout gh-pages
            mv dist/* /data/www/vue3
