name: scp files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master

    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
          username: 'root'
          server: ${{ secrets.REMOTE_HOST }} 
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './dist/*'
          remote_path: '/data/www/vue3'
          args: '-o ConnectTimeout=5'

  
