name: test
on: [push]
jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          rm -rf /data/www/temp
          mkdir /data/www/temp
          cd /data/www/temp
          git clone https://github.com/ibwei/vue3-base
          cd /data/www/temp/vue3-base
          cnpm install
          cnpm run build
          mv dist/* /data/www/vue3
          

